# curl -g \
# -X POST \
# -H "Content-Type: application/json" \
# -H "Origin: https://www.pgatour.com" \
# -H "Referer: https://www.pgatour.com" \
# -H "User-Agent: Mozilla/5.0 (Linux; Android 10; SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36" \
# -H "x-api-key: da2-gsrx5bibzbb4njvhl7t37wqyl4" \
# -d '{"operationName":"TournamentRecap","variables":{"tournamentId":"R2025011","limit":100},"query":"query TournamentRecap($tournamentId: String!, $limit: Int, $offset: Int) {\n  tournamentRecap(tournamentId: $tournamentId, limit: $limit, offset: $offset) {\n    tournamentId\n    durationDate\n    courses {\n      id\n      image\n      name\n      city\n      state\n      country\n      par\n      yardage\n    }\n    newsArticles {\n      id\n      headline\n      teaserHeadline\n      teaserContent\n      articleImage\n      url\n      shareURL\n      publishDate\n      updateDate\n      franchise\n      franchiseDisplayName\n      sponsor {\n        name\n        description\n        sponsorPrefix\n        logo\n        logoDark\n        image\n        websiteUrl\n        gam\n      }\n      brightcoveId\n      externalLinkOverride\n    }\n    videos {\n      ...VideoFragment\n    }\n  }\n}\n\nfragment VideoFragment on Video {\n  category\n  categoryDisplayName\n  created\n  description\n  descriptionNode {\n    ... on NewsArticleText {\n      __typename\n      value\n    }\n    ... on NewsArticleLink {\n      __typename\n      segments {\n        type\n        value\n        data\n        id\n        format {\n          variants\n        }\n        imageOrientation\n        imageDescription\n      }\n    }\n  }\n  duration\n  franchise\n  franchiseDisplayName\n  holeNumber\n  id\n  playerVideos {\n    firstName\n    id\n    lastName\n    shortName\n  }\n  poster\n  pubdate\n  roundNumber\n  shareUrl\n  shotNumber\n  startsAt\n  endsAt\n  thumbnailAsset {\n    imageOrg\n    imagePath\n  }\n  title\n  tournamentId\n  tourCode\n  year\n  accountId\n  gamAccountId\n  videoAccountId\n  seqHoleNumber\n  sponsor {\n    name\n    description\n    logoPrefix\n    logo\n    logoDark\n    image\n    websiteUrl\n    gam\n  }\n  pinned\n  contentTournamentId\n}"}' \
# https://orchestrator.pgatour.com/graphql

curl -g \
-X POST \
-H "Content-Type: application/json" \
-H "Origin: https://www.pgatour.com" \
-H "Referer: https://www.pgatour.com" \
-H "User-Agent: Mozilla/5.0 (Linux; Android 10; SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36" \
-H "x-api-key: da2-gsrx5bibzbb4njvhl7t37wqyl4" \
-d '{"operationName":"leaderboardV2","variables":{"id":"R2023100"},"query":"query leaderboardV2($id: ID!) {\n  leaderboardV2(id: $id) {\n    id\n   players\n   }\n  }\n "}' \
https://orchestrator.pgatour.com/graphql

# curl -g \
# -X POST \
# -H "Content-Type: application/json" \
# -H "Origin: https://www.pgatour.com" \
# -H "Referer: https://www.pgatour.com" \
# -H "User-Agent: Mozilla/5.0 (Linux; Android 10; SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36" \
# -H "x-api-key: da2-gsrx5bibzbb4njvhl7t37wqyl4" \
# -d '{"operationName":"TournamentOverview","variables":{"tournamentId":"R2023100"},"query":"query TournamentOverview($tournamentId: ID!) {\n  tournamentOverview(tournamentId: $tournamentId) {\n    beautyImage\n    overview {\n      label\n      value\n      detail\n      secondaryDetail\n      wide\n      smallCopy\n    }\n    defendingChampion {\n      displaySeason\n      title\n      playerId\n      displayName\n      score\n      total\n      countryCode\n      seed\n      headshot\n    }\n    defendingTeamChampion {\n      displaySeason\n      title\n      playerId\n      displayName\n      score\n      total\n      countryCode\n      seed\n      headshot\n    }\n    pastChampions {\n      displaySeason\n      title\n      playerId\n      displayName\n      score\n      total\n      countryCode\n      seed\n      headshot\n    }\n    pastTeamChampions {\n      players {\n        displaySeason\n        title\n        playerId\n        displayName\n        score\n        total\n        countryCode\n        seed\n        headshot\n      }\n    }\n    ticketsURL\n    webviewBrowserControls\n    tourcastURL\n    tourcastURLWeb\n    shareURL\n    eventGuideURL\n    augmentedReality {\n      holes {\n        holeNumber\n      }\n    }\n    courses {\n      id\n      image\n      name\n      city\n      state\n      country\n      overview {\n        label\n        value\n        detail\n        secondaryDetail\n        wide\n        smallCopy\n      }\n    }\n    formatType\n    activation {\n      title\n      sponsorLogo\n      sponsorLogoDark\n      data\n      description\n      detail\n    }\n  }\n}"}' \
# https://orchestrator.pgatour.com/graphql


# api key
# da2-gsrx5bibzbb4njvhl7t37wqyl4
# query for tournament schedule
#{"operationName":"Schedule","variables":{"tourCode":"R","year":"2022"},"query":"query Schedule($tourCode: String!, $year: String) {\n  schedule(tourCode: $tourCode, year: $year) {\n    completed {\n      tournaments {\n        tournamentName\n        id\n        beautyImage\n        champion\n        champions {\n          displayName\n          playerId\n        }\n        championEarnings\n        championId\n        city\n        country\n        countryCode\n        courseName\n        date\n        dateAccessibilityText\n        purse\n        sortDate\n        startDate\n        state\n        stateCode\n        status {\n          roundDisplay\n          roundStatus\n          roundStatusColor\n          roundStatusDisplay\n        }\n        ticketsURL\n        tourStandingHeading\n        tourStandingValue\n        tournamentLogo\n        display\n        sequenceNumber\n      }\n      month\n      monthSort\n      year\n    }\n    seasonYear\n    tour\n    seasonYear\n    upcoming {\n      month\n      year\n      tournaments {\n        id\n        date\n        startDate\n        dateAccessibilityText\n        tournamentName\n        tournamentLogo\n        city\n        state\n        stateCode\n        country\n        countryCode\n        courseName\n        champion\n        championId\n        champions {\n          displayName\n          playerId\n        }\n        championEarnings\n        beautyImage\n        status {\n          roundStatusDisplay\n          roundDisplay\n          roundStatus\n          roundStatusColor\n        }\n        sortDate\n        sequenceNumber\n        purse\n        ticketsURL\n        tourStandingHeading\n        tourStandingValue\n        tournamentLogo\n        tournamentName\n        display\n        sequenceNumber\n      }\n      monthSort\n    }\n    completed {\n      month\n      year\n      monthSort\n      tournaments {\n        id\n        date\n        startDate\n        dateAccessibilityText\n        tournamentName\n        tournamentLogo\n        city\n        state\n        stateCode\n        country\n        countryCode\n        courseName\n        champion\n        championId\n        champions {\n          displayName\n          playerId\n        }\n        championEarnings\n        beautyImage\n        status {\n          roundStatusDisplay\n          roundDisplay\n          roundStatus\n          roundStatusColor\n        }\n        sortDate\n        sequenceNumber\n        purse\n        ticketsURL\n        tourStandingHeading\n        tourStandingValue\n        display\n      }\n    }\n  }\n}"}

# curl -g \
# -X POST \
# -H "Content-Type: application/json" \
# -H "Origin: https://www.pgatour.com" \
# -H "Referer: https://www.pgatour.com" \
# -H "User-Agent: Mozilla/5.0 (Linux; Android 10; SM-G960U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36" \
# -H "x-api-key: da2-gsrx5bibzbb4njvhl7t37wqyl4" \
# -d '{"operationName":"ScorecardV2","variables":{"scorecardV2Id":"R2023545","playerId":"35310"},"query":"query ScorecardV2($scorecardV2Id: ID!, $playerId: ID!) {\n  scorecardV2(id: $scorecardV2Id, playerId: $playerId) {\n    ...ScorecardV2Fragment\n  }\n}\n\nfragment ScorecardV2Fragment on LeaderboardDrawerV2 {\n  tournamentName\n  id\n  currentHole\n  currentRound\n  player {\n    id\n    firstName\n    lastName\n    shortName\n    displayName\n    abbreviations\n    abbreviationsAccessibilityText\n    amateur\n    country\n    countryFlag\n    lineColor\n    seed\n    status\n    tourBound\n    assets {\n      ... on TourBoundAsset {\n        tourBoundLogo\n        tourBoundLogoDark\n      }\n    }\n  }\n  backNine\n  teeTime\n  groupNumber\n  playerState\n  roundScores {\n    roundNumber\n    currentRound\n    complete\n    groupNumber\n    firstNine {\n      total\n      totalLabel\n      parTotal\n      holes {\n        holeNumber\n        par\n        yardage\n        sequenceNumber\n        score\n        status\n        roundScore\n      }\n    }\n    secondNine {\n      total\n      totalLabel\n      parTotal\n      holes {\n        holeNumber\n        par\n        yardage\n        sequenceNumber\n        score\n        status\n        roundScore\n      }\n    }\n    parTotal\n    total\n    scoreToPar\n    courseName\n    courseId\n    tourcastURL\n    tourcastURLWeb\n    currentHole\n  }\n}"}' \
# https://orchestrator.pgatour.com/graphql
